### ISSUE TITLE
More informative `dvs status` results when files have not been queued

### ISSUE THREAD

**Issue by LizLusk** [A2-ai/devious#60]
As of at least devious 1.2.1, the results of `dvs status` do not seem to distinguish between a git repository that has had a Devious storage location initialized but does not have any files queued, and a git repository that has not yet had a Devious storage location initialized. It would be great if it could have a message like "The git repository is not associated with a Devious storage location"/"Devious storage has been initialized, but no files were queued"

**Comment by andriygm** [comment]
Thanks for the report Liz! Devious 2.0 definitely does a better job of this, but on that note there was still some improvement that could be done separating these states -- changes are made and you should see them next update!
